name: Update readme

on:
  schedule:
    - cron: "0 10,22 * * *"
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install

      - name: Generate readme
        env:
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN }}
        run: node ./src/index.js

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_PASSWORD }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-push-gpgsign: false

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Christopher Angelo
          commit_user_email: angelo@angeloanan.xyz
          commit_author: angelo@angeloanan.xyz
          commit_message: "chore(automation): update readme image"
          commit_options: "-S"
          file_pattern: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}